version: "3.7"
services:
  db-dev-container:
    container_name: db-dev-container
    image: postgres
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
        - database.env
    ports:
      - "7777:5432"
    networks:
      - db-dev-network
networks:
  db-dev-network:
    driver: bridge

# Run 'docker network create db-dev-network' before composing up